-- require("prototypes.damage-type")
require("prototypes.item.cursix-armor")
require("prototypes.item.cursix-equipment")
require("prototypes.equipment.cursix-equipment")
require("prototypes.item.cursix-module")
require("prototypes.item.cursix-entities")
require("prototypes.recipe.cursix-equipment")
require("prototypes.recipe.cursix-module")
require("prototypes.recipe.cursix-recipe")
require("prototypes.technologies.cursix-technology")
require("prototypes.cursix-equipment-grid")
require("prototypes.entity.cursix-entities")